export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST';
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS';
export const CONTRACT_LIST_FAILURE = 'CONTRACT_LIST_FAILURE';
